### ISSUE TITLE
draw.io Desktop - plugin install changed

### ISSUE THREAD

**Issue by mpern** [ariel-bentu/tam-drawio#11]
Hi!

It seems like the latest release of draw.io desktop (20.3.0) disabled support for the `plugins` array of the configuration object

Here is how i got it the plugin working:

1. Launch with plugin support enabled (`/path/to/draw.io --enable-plugins`)
2. Add tam-plugin via Extras -> Plugins... -> Add l External Plugins
3. Relaunch (with `--enable-plugins`)

**Comment by ariel-bentu** [comment]
Thanks for pointing this out. I adjusted there documentation to reflect this. see [here](https://github.com/ariel-bentu/tam-drawio#install-in-drawio-desktop)
