### ISSUE TITLE
Add installation-check to README.md

### ISSUE THREAD

**Issue by koppor** [ariel-bentu/tam-drawio#14]
I am a new user of draw.io. After following the installation steps (added at https://github.com/ariel-bentu/tam-drawio/issues/11), I am still not sure whether the plugin works.

After installation, the dialog for new diagrams does not show anything related to "Block Diagrams"

![image](https://user-images.githubusercontent.com/1366654/218190941-0702a283-c85e-4926-9ebf-7de1376ac380.png)

![image](https://user-images.githubusercontent.com/1366654/218190986-e133a686-1684-4d5e-bd9d-defd1e970904.png)

However, the plugin is listed in "Plugins"

![image](https://user-images.githubusercontent.com/1366654/218191046-165ddd80-b21e-4029-8085-db30b16b294a.png)

The current README.md guides well through the installation steps. I wish it had a "checkup" to show whether the plugin was installed well...

**Comment by ariel-bentu** [comment]
ok, added to the readme
