### ISSUE TITLE
Inclusion of a License

### ISSUE THREAD

**Issue by dellagustin-sap** [ariel-bentu/tam-drawio#3]
Hello Ariel, I could not find a License file on this repo, would you consider adding one?

Best Regards,
Guilherme.

**Comment by ariel-bentu** [comment]
Done

**Comment by dellagustin-sap** [comment]
Thanks! Just one remark, you left some place holders in the license: https://github.com/ariel-bentu/tam-drawio/blob/d7fd1a696ff9c8883cb603b37b272d7306d381c7/LICENSE#L189

**Comment by ariel-bentu** [comment]
ok, fixed - thanks
