### ISSUE TITLE
Visual glitch with connectors

### ISSUE THREAD

**Issue by Maev4l** [ariel-bentu/tam-drawio#7]
Hi folks,

I am using this plugin with Draw.io desktop (19.0.1) on MacOS.
I noticed a visual glitch with the connectors (communication channels and read/write requests): After moving connectors, they are still shown at their initial positions, but in blue.
I think the attached image explained it better:

![glitch](https://user-images.githubusercontent.com/6023829/173785222-adba256b-ae23-48ca-bd20-2d9a323bee34.jpg)
.

**Comment by ariel-bentu** [comment]
fixed
