### ISSUE TITLE
How to draw bi-directional and unidirectional channels?

### ISSUE THREAD

**Issue by janothan** [ariel-bentu/tam-drawio#8]
In the `TAM / Block` section, I can find request-response channels but I am missing bi-directional (no R ▶) and unidirectional (→○→) channels.

**Comment by ariel-bentu** [comment]
The plug-in adds two buttons to the toolbar. One of them is changing the directions of request-response arrow. It has 3 states: bidi, and two uni-directional. 
in bidirectional, the R is removed. 
Are you expecting something more?

**Comment by janothan** [comment]
Thank you for your prompt reply! In fact, I was not aware of the "Flip Use Direction" menu item.
I am still missing the "unidirectional communication channel" as visible [here](http://www.fmc-modeling.org/download/notation_reference/Reference_Sheet-Block_Diagram.pdf).

**Comment by ariel-bentu** [comment]
Hi,
currently I'm not planning to do this. you are welcome to contribute. I close from now, and will consider in future enhancements.
