### ISSUE TITLE
Unknown TypeError when adding TAM element

### ISSUE THREAD

**Issue by denisMihaylov** [ariel-bentu/tam-drawio#9]
I have installed the latest tam diagram plugin in Drawio. I am using version 19.0.3 which has plugins disabled by default and I have managed to enable the TAM plugin. Now I see the elements but when I try to add an element to the canvas I get the same error for each element: 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/7723851/178538028-27af3051-4278-4715-bf3d-c60dc7c873d6.png">
When I close the dialog everything is fine, but still it happens each time I add

**Comment by denisMihaylov** [comment]
Now that I had more time to poke around it seems that this is not popping up for every element. It happens for the request arrows and for some of the shapes in the Block section, but for others it does not happen

**Comment by ariel-bentu** [comment]
fix with this commit https://github.com/ariel-bentu/tam-drawio/commit/90d1ceb06f79b6c5c572738c5efd54c2d71e081f
